version: "3.9"
services:
  nginx_main:
    build: 
     context: ./nginx
     dockerfile: Dockerfile
    restart: always
    ports:
      - "8094:80"
    volumes:
    - my-nfs-volume:/nfs
  Admin_mode_1:
    image: nginx
    volumes:
      - my-nfs-volume:/nfs
    restart: always
    ports:
      - "8095:80"
  Admin_mode_2:
    image: nginx
    volumes:
      - my-nfs-volume:/nfs
    restart: always
    ports:
      - "8096:80"
  Admin_mode_3:
    image: nginx
    volumes:
      - my-nfs-volume:/nfs
    restart: always
    ports:
      - "8096:80"
  webA:
    image: nginx 
    restart: always
    ports:
      - "8091:80"
    volumes:
    - my-nfs-volume:/nfs
  webB:
    image: nginx
    restart: always
    ports:
      - "8092:80"
    volumes:
    - my-nfs-volume:/nfs
  webC:
    image: nginx
    restart: always
    ports:
      - "8093:80"
    volumes:
    - my-nfs-volume:/nfs


volumes:  
 my-nfs-volume:
   name: my-nfs-volume
   driver_opts:
      type: "nfs"
      o: "username=mis,password=M@gic2023,addr=192.168.56.11,soft,ro"
      device: ":/home/sharedocker"